= ESO Data Dumper

An Elder Scrolls Online addon for dumping data for use in other applications.
The end goal would be to have this data fed into a web app powered by Rails,
and then served via an API for an Ember or Angular single-page app. A girl
can dream.

If you actually want to use this add-on in your own game (dunno why, but anyway)
clone the repo into a `C:\Users\[your username]\My Documents\Elder Scrolls Online\live\addons\Data Dumper`
folder. Start the game, and you will be able to enable the "Data Dumper" addon.

== To use the addon:

In the chat winodow:
`/dump achievements` will save all achievement data.
`/dump dyes` will save all dye data.

Then either quit the game or `/reloadui` to have the data saved out to file.

The file containing all of the data will be found in:
`C:\Users\[your username]\My Documents\Elder Scrolls Online\live\SavedVariables\DataDumper.lua`

This is a valid Lua file meant to be read and interpreted by another Lua script - and here's one I prepared earlier!

=== JSON encoder

JSON is a much friendlier format than Lua! So here's how to convert it to JSON format!

Requirements:

* Lua 5.2
* dkjson 2.5-2

Run `lua JsonEncoder \path\to\your\DataDumper.lua` and you'll get a nice `output` folder in your add-on folder, filled
with JSON goodies. Yay!

== If it doesn't work:

File an issue.

== Features coming soon:

See the TODO file.
